# Moved all per-Client, Slack specific values to Environment variables
# note: slack user name is not overridable if using incoming web hook (see https://api.slack.com/incoming-webhooks)

#message_truncate_length: 2000 # no truncate
message_truncate_length: 239
message_truncate_lines: 3 
message_strip_new_lines: false
original_message_debug_logging: true
# 30 characters/line (mobile)
# 80 characters/line (desktop). Note Slack recommends 75 characters/line for no word-wrapping
# lcm 30, 80 is 240
# Leave 1 character for …